import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ratan
 */
public class game extends javax.swing.JFrame {
 Timer t= new Timer(80,new ActionListener(){
    public void actionPerformed(ActionEvent e) {
        int i= Integer.parseInt(jLabel2.getText());
        int j= i%8;
        i++;
        jLabel2.setText(""+i);
        jLabel2.setVisible(false);
        switch(j)
        {
            case 0 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s1.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S1.png")));
                     break;
            case 1 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s2.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S2.png")));
                    break;
            case 2 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s3.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S3.png")));
                    break;     
            case 3 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s4.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S4.png")));
                    break;
            case 4 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s5.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S5.png")));
                    break;     
            case 5 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s6.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S6.png")));
                    break;
            case 6 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s7.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S7.png")));                 
                    break;
            case 7 :jLabel3.setIcon(new ImageIcon(getClass().getResource("p1//s1.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("P2//S1.png")));
                    break;    
        }
    }
    
});   
int i=100;
int j=100;
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
       
        t.start();
                         jProgressBar1.setValue(100);
                         jProgressBar2.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(456, 356));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setText("0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 70, 6, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p1/s1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 210, 90, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/P2/S1.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 220, 57, 100);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 30, 180, 30);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(260, 30, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BR13.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
int keyCode =evt.getKeyCode();
   if(keyCode== KeyEvent.VK_A)
   {
       jProgressBar2.setValue(i=i-1);
   }
   if(keyCode== KeyEvent.VK_L)
   {
       jProgressBar1.setValue(j=j-1);
   }
   if(jProgressBar2.getValue()==0)
   {
       JOptionPane.showMessageDialog(this,"Player 1 won the game");
       dispose();
   }
   if(jProgressBar1.getValue()==0)
   {
       JOptionPane.showMessageDialog(this,"Player 2 won the game");
       dispose();
   }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
